<MainScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 20

        Label:
            text: "Innen-Temperatur"
            font_size: "24sp"

        Label:
            text: "{:.1f} °C".format(root.state.temperature_inside)
            font_size: "40sp"

        Label:
            text: "Innen-Luftfeuchtigkeit"
            font_size: "24sp"

        Label:
            text: "{:.1f} °C".format(root.state.humidity_inside)
            font_size: "40sp"